server.port=8081

spring.mongodb.uri=mongodb+srv://tgldrchn:Tuguldur%400919@cluster0.ed9xmhc.mongodb.net/profile_db?retryWrites=true&w=majority&appName=Cluster0

soap.url=${SOAP_URL:http://localhost:8081/ws/auth}